{% set name = "pytest-deadfixtures" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest-deadfixtures-{{ version }}.tar.gz
  sha256: ca15938a4e8330993ccec9c6c847383d88b3cd574729530647dc6b492daa9c1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pytest >=3.0.0

test:
  imports:
    - pytest_deadfixtures
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jllorencetti/pytest-deadfixtures
  summary: A simple plugin to list unused fixtures in pytest
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
