{% set name = "pytest-deadfixtures" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 08704a1301ee4c631d33f70af4c48ac5904ee4d48656161fa66e6eca07491492

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pytest >=3.0.0

test:
  imports:
    - pytest_deadfixtures
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jllorencetti/pytest-deadfixtures
  summary: A simple plugin to list unused fixtures in pytest
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
